config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :profiles, except: %i[show]

  resources :newsposts, only: %i[index]
  resources :articles, only: %i[index show]
  resources :downloads, only: %i[index show]
  resources :posts, except: %i[index show]

  root 'newsposts#index'
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

# Handles everything related to User CRUD.
class ProfilesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action -> { @user = User.new }, only: %i[new create]
  before_action(
    -> { @user = User.find(params[:id]) }, except: %i[index new create]
  )

  def index
    @users = User.all
  end

  def show; end

  def new
    render :edit
  end

  def create
    if @user.update(profile_params)
      redirect_to profiles_path
    else
      render :edit
    end
  end

  def edit; end

  def update
    if @user.update(profile_params)
      redirect_to profiles_path
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to profiles_path
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(:name, :avatar, :about)
  end
end

app/views/profiles/edit.html.erb
<% url = @user.new_record? ? profiles_path : profile_path(@user) %>

<h1>Edit Profile</h1>

<%= render 'partials/errors', model: @user %>

<%= form_for @user, url: url do |f| %>
  <label>Display Name</label><br>
  <%= f.text_field :name %><br><br>
  <label>Upload a new avatar?</label><br>
  <%= f.file_field :avatar %><br><br>
  <label>About</label><br>
  <%= f.text_area :about %>
  <hr>
  <button>Save changes</button>
<% end %>

app/views/profiles/index.html.erb
<% title = t('common.person').titleize.pluralize %>
<% content_for(:title, title) %>
<% content_for(:metadata, ogp_tags(title, profiles_url)) %>

<% @redcarpet ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML) %>

<% unless @users.exists? %>
  <div class='nothing-to-show'>There's nothing to see here right now...</div>
<% end %>

<% @users.each do |user| %>
  <div class='post'>
    <div class='header'>
      <%= avatar(user) %>
      <%= content_tag(:div, user, class: 'title') %>
    </div>
    <div class='footer'>
      <%= link_to 'Newsposts', newsposts_path(user: user.id) %>
      <%= link_to 'Articles', articles_path(user: user.id) %>
      <%= link_to 'Downloads', downloads_path(user: user.id) %>
    </div>
    <div class='content'>
      <%= @redcarpet.render(user.about || 'rly makes u think... 🤔').html_safe %>
    </div>
  </div>
<% end %>