config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :profiles, except: %i[show]

  resources :newsposts, only: %i[index]
  resources :articles, only: %i[index show]
  resources :downloads, only: %i[index show]
  resources :posts, except: %i[index show]

  root 'newsposts#index'
end

app/controllers/downloads_controller.rb
# frozen_string_literal: true

# This handles anything that should appear specifically under "Downloads".
class DownloadsController < ApplicationController
  def index
    @downloads = available_posts.download.order(created_at: :desc)
  end

  def show
    @download = available_posts.download.find(params[:id])
  end
end

app/views/downloads/index.html.erb
<% title = t('common.download').titleize.pluralize %>
<% content_for(:title, title) %>
<% content_for(:metadata, ogp_tags(title, downloads_url)) %>

<% unless @downloads.exists? %>
  <div class='nothing-to-show'><%= t('views.articles.none') %></div>
<% end %>

<% @downloads.each do |download| %>
  <div class='post-summary'>
    <%= link_to download, download_path(download), class: 'title' %>
    <%= content_tag :span, download.upload_type.titleize, class: 'genre' %>
    <% if download.upload.attached? %>
      <%= content_tag :span, number_to_human_size(download.upload.blob.byte_size), class: 'size' %>
    <% else %>
      <%= content_tag :span, 'N/A', class: 'size' %>
    <% end %>
    <% if current_user %>
      <%= content_tag :span, visibility_text(download), class: 'visible' %>
    <% end %>
    <%= content_tag :span, download.user, class: 'user' %>
    <%= content_tag :span, download.created_at, class: 'date' %>
  </div>
<% end %>

app/views/downloads/show.html.erb
<% content_for(:title, @download) %>
<% content_for(:metadata, ogp_tags_for(@download)) %>

<div class='download'>
  <div class='preview'>
    <% if @download.upload_type == 'image' %>
      <%= image_tag url_for(@download.upload) %>
    <% elsif @download.upload_type == 'video' %>
      <%= content_tag :video, '', src: url_for(@download.upload), controls: true %>
    <% elsif @download.upload_type == 'audio' %>
      <%= content_tag :audio, '', src: url_for(@download.upload), controls: true %>
    <% end %>
  </div>
  <div class='direct'>
    <% if @download.upload.attached? %>
      <%= link_to url_for(@download.upload) do %>
        Download <%= @download.upload.filename %>
        (<%= number_to_human_size(@download.upload.blob.byte_size) %>)
      <% end %>
    <% else %>
      <div class='deleted'><%= t('views.downloads.deleted') %></div>
    <% end %>
  </div>
</div>

<%= render 'posts/embed', post: @download %>