config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :profiles, except: %i[show]

  resources :newsposts, only: %i[index]
  resources :articles, only: %i[index show]
  resources :downloads, only: %i[index show]
  resources :posts, except: %i[index show]

  root 'newsposts#index'
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# This handles anything that should appear specifically under "Articles".
class ArticlesController < ApplicationController
  def index
    @articles = available_posts.article.order(created_at: :desc)
  end

  def show
    @article = available_posts.article.find(params[:id])
  end
end

app/views/articles/index.html.erb
<% title = t('common.article').titleize.pluralize %>
<% content_for(:title, title) %>
<% content_for(:metadata, ogp_tags(title, articles_url)) %>

<% unless @articles.exists? %>
  <div class='nothing-to-show'><%= t('views.articles.none') %></div>
<% end %>

<% @articles.each do |article| %>
  <div class='post-summary'>
    <%= link_to article, article_path(article), class: 'title' %>
    <% if current_user %>
      <%= content_tag :span, visibility_text(article), class: 'visible' %>
    <% end %>
    <%= content_tag :span, article.user, class: 'user' %>
    <%= content_tag :span, article.created_at, class: 'date' %>
  </div>
<% end %>

app/views/articles/show.html.erb
<% content_for(:title, @article) %>
<% content_for(:metadata, ogp_tags_for(@article)) %>

<%= render 'posts/embed', post: @article %>