config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :profiles, except: %i[show]

  resources :newsposts, only: %i[index]
  resources :articles, only: %i[index show]
  resources :downloads, only: %i[index show]
  resources :posts, except: %i[index show]

  root 'newsposts#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#">
  <head>
    <meta charset='utf-8'>
    <%= content_for(:metadata) %>
    <title>
      <%= [content_for(:title), t('common.website')].compact.join(' | ') %>
    </title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Fonts: -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway&family=Source+Code+Pro&display=swap" rel="stylesheet">
    <!-- Automatic syntax highlighting for code blocks: -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <!-- Real-time Markdown preview: -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/commonmark/0.28.1/commonmark.min.js'></script>
  </head>
  <body>
    <div class='page-header'>
      <%= link_to(t('common.website'), '/', class: 'logo') %>
      <div class = 'random-tagline'><%= random_tagline %></div>
    </div>
    <div class='page-container'>
      <div class='page-navigation'>
        <div class='general-actions'>
          <%= link_to(t('common.newspost').pluralize, '/') %>
          <%= link_to(t('common.article').pluralize, articles_path) %>
          <%= link_to(t('common.person').pluralize, profiles_path) %>
          <%= link_to(t('common.download').pluralize, downloads_path) %>
        </div>
        <% if current_user %>
          <div class='user-actions'>
            <%= link_to 'Upload File', new_post_path(category: 'download') %>
            <%= link_to 'New Article', new_post_path %>
            <%= link_to 'Settings', edit_profile_path(current_user) %>
            <%= link_to 'Account', edit_user_registration_path %>
            <%= link_to(
              'Log Out',
              destroy_user_session_path,
              method: :delete,
              data: { confirm: 'Are you sure that you want to log out?' }
            ) %>
          </div>
        <% end %>

      </div>
      <div class='page-content'>
        <%= yield %>
      </div>
    </div>
    <div class='page-footer'>© 2018-2019 Tom Dennis</div>
  </body>
</html>
<% flash.clear %>